"""同一DB内の運用状態。Transactionの開始・終了はApplicationが所有する。"""

from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True, slots=True)
class OwnerClaim:
    status: str
    scope: str


class OperationOwnerPort(Protocol):
    def hold(
        self, token: str, expected_scope: str | None = None
    ) -> AbstractContextManager[OwnerClaim]: ...
    def fence(self) -> AbstractContextManager[OwnerClaim]: ...


class OperationControlTransaction(Protocol):
    def artifact_references(self) -> tuple[str, ...]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def mode(self) -> str: ...
    def set_mode(self, mode: str) -> None: ...
    def active_count(self) -> int: ...
    def unsettled_count(self) -> int: ...
    def reserve(
        self, token: str, kind: str, *, request_id: str = "", owner_scope: str = ""
    ) -> None: ...
    def owners(self) -> tuple[dict[str, Any], ...]: ...
    def start_restore(self, token: str, owner_scope: str, purpose: str) -> None: ...
    def finish_restore(self, token: str, status: str) -> None: ...
    def restore_record(self) -> dict[str, Any] | None: ...
    def release(self, token: str) -> None: ...
    def record_refusal(self) -> None: ...
    def refusals(self) -> int: ...


class OperationControlStore(Protocol):
    def transaction(self) -> AbstractContextManager[OperationControlTransaction]: ...
    def ownership(self) -> OperationOwnerPort: ...
    def new_token(self) -> str: ...
    def identity(self) -> str: ...


class OperationAdmissionPort(Protocol):
    def admission(
        self, request_id: str, *, kind: str = "intake"
    ) -> AbstractContextManager[None]: ...
    def restoration(self, *, purpose: str = "UNSPECIFIED") -> AbstractContextManager[None]: ...
    def stop(self) -> None: ...
    def resume(self) -> None: ...
    def active_count(self) -> int: ...
    def refusals(self) -> int: ...
